package com.duckblade.osrs.sailing.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ObjectID;

@Getter
@RequiredArgsConstructor
public enum Port
{

	ALDARIN("ALDRN", 8605, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ALDARIN),
	ARDOUGNE("ARDY", 8596, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ARDOUGNE),
	BRIMHAVEN("BRIM", 8595, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_BRIMHAVEN),
	CAIRN_ISLE("CAIRN", 8602, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CAIRN_ISLE),
	CATHERBY("CATH", 8593, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CATHERBY),
	CIVITAS_ILLA_FORTIS("FORTS", 8600, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CIVITAS_ILLA_FORTIS),
	CORSAIR_COVE("CORSR", 8601, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_CORSAIR_COVE),
	DEEPFIN_POINT("DPFIN", 8613, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_DEEPFIN_POINT),
	ENTRANA("ENTR", 8599, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ENTRANA),
	ETCETERIA("ETC", 8611, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_ETCETERIA),
	HOSIDIUS("HOSDS", 8591, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_HOSIDIUS),
	JATIZSO("JATIZ", 8614, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_JATIZSO),
	LANDS_END("LANDS", 8589, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_LANDS_END),
	LUNAR_ISLE("LUNAR", 8618, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_LUNAR_ISLE),
	MUSA_POINT("MUSA", 8590, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_MUSA_POINT),
	NEITIZNOT("NEITZ", 8615, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_NEITIZNOT),
	PISCATORIS("PSCTR", 8617, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PISCATORIS),
	PORT_KHAZARD("KHZRD", 8597, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_KHAZARD),
	PORT_PISCARILIUS("PSCRL", 8594, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_PISCARILIUS),
	PORT_ROBERTS("ROBRT", 8608, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_ROBERTS),
	PORT_SARIM("SARIM", 8597, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_SARIM),
	PORT_TYRAS("TYRAS", 8612, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PORT_TYRAS),
	PRIFDDINAS("PRIF", 8616, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PRIFDDINAS),
	RED_ROCK("REDRK", 8609, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RED_ROCK),
	RELLEKKA("RELL", 8610, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RELLEKKA),
	RUINS_OF_UNKAH("UNKAH", 8606, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_RUINS_OF_UNKAH),
	SUNSET_COAST("SUNST", 8603, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_SUNSET_COAST),
	THE_PANDEMONIUM("PAND", 8588, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_PANDEMONIUM),
	THE_SUMMER_SHORE("SUMMR", 8604, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_THE_SUMMER_SHORE),
	VOID_KNIGHTS_OUTPOST("VOID", 8607, ObjectID.DOCK_LOADING_BAY_LEDGER_TABLE_VOID_KNIGHTS_OUTPOST),
	;

	private final String shortCode;
	private final int dbRowID;
	private final int ledgerTableID;

	public static Port findByID(int id)
	{
		for (Port port : Port.values())
		{
			if (port.getDbRowID() == id)
			{
				return port;
			}
		}

		return null;
	}

	public static Port findByLedgerTableID(int id)
	{
		for (Port port : Port.values())
		{
			if (port.getLedgerTableID() == id)
			{
				return port;
			}
		}
		return null;
	}
}
